# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.cache/wt [current_project]
set_property parent.project_path /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/rewingchow/board_files/} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/src/lut14.mem
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.srcs/sources_1/imports/16/weights_layer2_3.mem
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.srcs/sources_1/imports/16/bias_layer3.mem
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.srcs/sources_1/imports/16/weights_layer1_2.mem
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/edit_NeuralNetHandWritten_v1_0.srcs/sources_1/imports/16/bias_layer2.mem
}
read_verilog -library xil_defaultlib {
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/src/NeuralNet.v
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/src/RelU.v
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/src/Sigmoid.v
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/src/VecMult.v
}
read_verilog -library "" {
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/hdl/NeuralNetHandWritten_v1_0_M00_AXIS.v
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/hdl/NeuralNetHandWritten_v1_0_S00_AXIS.v
  /home/rewingchow/NN_16/AXISHandWritten_16/AXISHandWritten/NeuralNetHandWritten_1_0/hdl/NeuralNetHandWritten_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top NeuralNetHandWritten_v1_0 -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NeuralNetHandWritten_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NeuralNetHandWritten_v1_0_utilization_synth.rpt -pb NeuralNetHandWritten_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
